application:
  name: workshop-server
  version: 1.0.0-SNAPSHOT

server:
  port: 11434

spring:
  cloud:
    consul:
      discovery:
        serviceName: ${spring.application.name}-dev
        port: ${server.port}
        tags:
          - workshop
          - spring
          - accesa
        healthCheckUrl: http://localhost:${server.port}/actuator/health
        healthCheckInterval: 5s
  datasource:
    url: jdbc:h2:mem:training
    #url: jdbc:h2:file:C:/data/training
    driverClassName: org.h2.Driver
    username: sa
    password: pa
  h2:
    console:
      enabled: true
#  jpa:
#    propoerties:
#      hibernate:
#        dialect: org.hibernate.dialect.H2Dialect

db:
  default:
    driver: org.postgresql.Driver
    url: jdbc:postgresql://postgres:5432/postgres
    user: postgres
    password: admin
    pool:
      size: 10

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

endpoints:
  shutdown:
    enabled: true



